let matches=[],current=new Date(),activeFilter="Vše";
const months=["Leden","Únor","Březen","Duben","Květen","Červen","Červenec","Srpen","Září","Říjen","Listopad","Prosinec"];
const pad=n=>String(n).padStart(2,"0"), key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
async function load(){try{let r=await fetch("data/matches.json?"+Date.now(),{cache:"no-store"});matches=await r.json();document.getElementById("syncStatus").textContent="Aktualizováno z dat ČVS";render()}catch(e){document.getElementById("syncStatus").textContent="Data se nepodařilo načíst";}}
function render(){document.getElementById("monthTitle").textContent=`${months[current.getMonth()]} ${current.getFullYear()}`;let g=document.getElementById("calendar");g.innerHTML="";
let first=new Date(current.getFullYear(),current.getMonth(),1),last=new Date(current.getFullYear(),current.getMonth()+1,0),start=(first.getDay()+6)%7;
for(let i=0;i<start;i++)g.insertAdjacentHTML("beforeend",'<div class="day muted"></div>');
for(let d=1;d<=last.getDate();d++){let dt=new Date(current.getFullYear(),current.getMonth(),d),k=key(dt),cl="day";if(k===key(new Date()))cl+=" today";if(matches.some(m=>m.date===k&&(activeFilter==="Vše"||m.category===activeFilter)))cl+=" has-event";g.insertAdjacentHTML("beforeend",`<div class="${cl}">${d}</div>`)}
renderEvents()}
function renderEvents(){let box=document.getElementById("events"),month=key(current).slice(0,7),list=matches.filter(m=>m.date.startsWith(month)&&(activeFilter==="Vše"||m.category===activeFilter)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));box.innerHTML=list.length?list.map(m=>`<article class="event"><div class="event-top"><span>${new Intl.DateTimeFormat("cs-CZ",{weekday:"long",day:"numeric",month:"long"}).format(new Date(m.date+"T12:00:00"))} · ${m.time}</span><span class="badge">${m.category}</span></div><div class="event-title">${m.home} – ${m.away}</div><div class="event-meta">📍 ${m.venue||"Místo dle ČVS"} · ${m.competition}</div>${m.score?`<div class="score">${m.score}</div>`:""}</article>`).join(""):'<div class="event">Žádné zápasy pro tento měsíc.</div>'}
document.getElementById("prevBtn").onclick=()=>{current.setMonth(current.getMonth()-1);render()};document.getElementById("nextBtn").onclick=()=>{current.setMonth(current.getMonth()+1);render()};document.getElementById("todayBtn").onclick=()=>{current=new Date();render()};
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeFilter=b.dataset.filter;render()});
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");let id=t.dataset.tab;document.querySelectorAll("main,.panel").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden")});
load();
