const matches=[
{"date":"2026-09-26","time":"14:00","cat":"U18","comp":"Extraliga U18","home":"SK Prosek Praha B","away":"INLAB SK Meteor Praha","place":"SH SK Prosek","address":"Lovosická 559/32, Praha 9"},
{"date":"2026-10-03","time":"10:00","cat":"U18","comp":"Extraliga U18","home":"VK Lvi Praha","away":"SK Prosek Praha","place":"Praha","address":""},
{"date":"2026-10-03","time":"14:00","cat":"U18","comp":"Extraliga U18","home":"VK Ostrava","away":"SK Prosek Praha","place":"Ostrava","address":""},
{"date":"2026-10-04","time":"09:00","cat":"U18","comp":"Extraliga U18","home":"SK Prosek Praha","away":"VK Dukla Liberec","place":"Praha","address":""},
{"date":"2026-10-04","time":"13:00","cat":"U18","comp":"Extraliga U18","home":"VK Jirkov","away":"SK Prosek Praha","place":"Jirkov","address":""},
{"date":"2026-10-10","time":"10:00","cat":"U20","comp":"Extraliga U20","home":"VK Brno","away":"SK Prosek Praha","place":"Brno","address":""},
{"date":"2026-10-10","time":"14:00","cat":"U20","comp":"Extraliga U20","home":"SK Volejbal Klatovy","away":"SK Prosek Praha","place":"Klatovy","address":""},
{"date":"2026-10-11","time":"09:00","cat":"U20","comp":"Extraliga U20","home":"SK Prosek Praha","away":"Kladno volejbal cz","place":"Praha","address":""},
{"date":"2026-10-11","time":"13:00","cat":"U20","comp":"Extraliga U20","home":"AERO Odolena Voda","away":"SK Prosek Praha","place":"Odolena Voda","address":""},
{"date":"2026-10-17","time":"12:00","cat":"U22","comp":"Extraliga U22","home":"VK Ostrava","away":"SK Prosek Praha","place":"Ostrava","address":""},
{"date":"2026-10-17","time":"18:00","cat":"U22","comp":"Extraliga U22","home":"SK Volejbal Kolín","away":"SK Prosek Praha","place":"Kolín","address":""},
{"date":"2026-10-18","time":"11:00","cat":"U22","comp":"Extraliga U22","home":"SK Prosek Praha","away":"TJ Slavia Hradec Králové","place":"Praha","address":""}
];
let current=new Date(2026,8,25),cat="Vše";
const months=["leden","únor","březen","duben","květen","červen","červenec","srpen","září","říjen","listopad","prosinec"];
const pad=n=>String(n).padStart(2,"0"),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function shown(){return matches.filter(m=>cat==="Vše"||m.cat===cat)}
function render(){document.getElementById("month").textContent=`${months[current.getMonth()]} ${current.getFullYear()}`;let g=document.getElementById("calendar");g.innerHTML="";let f=new Date(current.getFullYear(),current.getMonth(),1),last=new Date(current.getFullYear(),current.getMonth()+1,0),start=(f.getDay()+6)%7;for(let i=0;i<start;i++)g.insertAdjacentHTML("beforeend",'<div class="day muted"></div>');for(let d=1;d<=last.getDate();d++){let dt=new Date(current.getFullYear(),current.getMonth(),d),k=key(dt),es=shown().filter(m=>m.date===k);g.insertAdjacentHTML("beforeend",`<div class="day ${k===key(new Date())?"today":""}">${d}${es.slice(0,2).map(e=>`<span class="event-dot">${e.time} ${e.cat}</span>`).join("")}</div>`)}renderEvents()}
function renderEvents(){let list=shown().filter(m=>m.date.startsWith(key(current).slice(0,7))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));document.getElementById("events").innerHTML=list.length?list.map((m,i)=>`<article class="event" onclick="openDetail(${matches.indexOf(m)})"><div class="event-top"><span>${new Intl.DateTimeFormat("cs-CZ",{weekday:"long",day:"numeric",month:"long"}).format(new Date(m.date+"T12:00"))} · ${m.time}</span><span class="badge">${m.cat}</span></div><div class="event-title">${m.home} – ${m.away}</div><div class="event-meta">📍 ${m.place}</div></article>`).join(""):'<div class="event">Žádné zápasy.</div>'}
function openDetail(i){let m=matches[i];document.getElementById("detailBody").innerHTML=`<div class="detail-hero"><span class="badge">${m.cat}</span><div>${m.comp}</div><div>${new Intl.DateTimeFormat("cs-CZ",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(m.date+"T12:00"))}</div><h2>${m.time}</h2><div class="teams"><span>${m.home}</span><b class="versus">–</b><span>${m.away}</span></div></div><div class="info"><div class="info-row"><span>📅 Datum</span><span>${m.date}</span></div><div class="info-row"><span>◷ Čas</span><span>${m.time}</span></div><div class="info-row"><span>🏆 Soutěž</span><span>${m.comp}</span></div><div class="info-row"><span>🏟 Hala</span><span>${m.place}</span></div><div class="info-row"><span>📍 Adresa</span><span>${m.address||"Dle ČVS"}</span></div></div>`;document.getElementById("detail").classList.remove("hidden")}
document.getElementById("close").onclick=()=>document.getElementById("detail").classList.add("hidden");
document.getElementById("prev").onclick=()=>{current.setMonth(current.getMonth()-1);render()};document.getElementById("next").onclick=()=>{current.setMonth(current.getMonth()+1);render()};document.getElementById("today").onclick=()=>{current=new Date();render()};document.getElementById("refresh").onclick=()=>render();
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.cat;render()});
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");let id=t.dataset.page;document.getElementById("app").classList.toggle("hidden",id!=="calendarPage");document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));if(id!=="calendarPage")document.getElementById(id).classList.remove("hidden")});
document.getElementById("addTraining").onclick=()=>alert("Přidání tréninku doplníme v další verzi.");
render();